Article and articlelist stilization
08-pk-team-03/react-project-kitchen-frontend pull request #14
Opened 2022-02-08 07:05 UTC by AlexanderIlinykhDev

2022-02-08 12:40 UTC, gold22 requested changes

2022-02-08 12:40 UTC, gold22 commented on src/components/ArticleList.js
> +import ArticlePreview from "./ArticlePreview/ArticlePreview";
Кавычки должны быть одинарными, линтер должен на них по идее ругаться. Используй команду yarn lint если IDE не показывает ворнинги. Комментарий ко  всем файлам относится.

2022-02-08 12:40 UTC, gold22 commented on src/components/ArticleList.js
> +import React from "react";
Сначала внешние компоненты импортятся, потом уже внутренние. Линтер должен это подсказывать. Комментарий ко  всем файлам относится.

2022-02-08 12:40 UTC, gold22 commented on src/components/ArticleList.js
> +    return <div className="article-preview">Loading...</div>;
Измененные файлы нужно переименовать в *.jsx. Комментарий ко  всем файлам относится.

2022-02-08 12:40 UTC, gold22 commented on src/components/App/App.js
> +import Editor from '../Editor/Editor';
Тут мои изменения похоже попали, нужно их убрать из реквеста.

2022-02-08 12:40 UTC, gold22 commented on src/components/ArticlePreview/ArticlePreview.js
> +    <>
Тут фрагмент <> вроде не нужен, есть же общий для всех <div>.

2022-02-08 12:40 UTC, gold22 commented on src/components/Editor/Editor.jsx
> +import React from 'react';
Мои изменения нужно убрать из реквеста.

2022-02-08 12:40 UTC, gold22 commented on src/components/common/Tag/Tag.jsx
> +import React from 'react';
Тот тоже должны только твои изменения быть.

2022-02-08 12:40 UTC, gold22 commented on src/components/common/Tag/Tag.jsx
> +const Tag = ({ text, closable, onClose, white = false }) => (
Дефолтное значение для white необходимо и достаточно в Tag.defaultProps прописать.

2022-02-08 12:40 UTC, gold22 commented on src/components/common/Tag/Tag.jsx
> +  <div className={`${tagStyles.container} + ${white && tagStyles.white}`}>
Если white будет false то строка 'false' добавится к стилю. Тут нужно тернарный оператор использовать ? : .
+ тут похоже лишний, строки внутри ` ` и так сложатся.

2022-02-08 12:40 UTC, gold22 commented on src/images/icons.jsx
> +    <title id="title">Like default icon</title>
title тут не лишнее?

2022-02-08 12:40 UTC, gold22 commented on src/images/Vector (3).svg
> +<path d="M19.84 1.61183C19.3292 1.10083 18.7228 0.695472 18.0554 0.41891C17.3879 0.142347 16.6725 0 15.95 0C15.2275 0 14.5121 0.142347 13.8446 0.41891C13.1772 0.695472 12.5708 1.10083 12.06 1.61183L1
Если это иконка то ее нужно в icons.jsx добавить.

2022-02-08 12:40 UTC, gold22 commented on src/images/heart.svg
> +<svg width="22" height="19" viewBox="0 0 22 19" fill="none" xmlns="http://www.w3.org/2000/svg">
Если это иконка то ее нужно в icons.jsx добавить.

2022-02-08 16:51 UTC, gold22 commented on src/components/Home/MainView.js
> +      <li className='nav-item'>
В HTML как раз наоборот, нужны двойные кавычки ", одинарные только в JS/TS коде.

2022-02-08 16:54 UTC, gold22 commented on src/components/common/ArticleList/ArticleList.jsx
> +    return <div className='article-preview'>Loading...</div>;
Не переведено.

2022-02-08 16:56 UTC, gold22 commented on src/components/common/ArticleList/ArticleList.jsx
> +import React from 'react';
В common нужно двигать только компоненты которые используются больше чем в одном месте.

2022-02-08 16:57 UTC, gold22 commented on src/components/common/ArticlePreview/ArticlePreview.jsx
> +import React from 'react';
В common нужно двигать только компоненты которые используются больше чем в одном месте.

2022-02-09 06:15 UTC, AlexanderIlinykhDev commented on src/components/common/ArticleList/ArticleList.jsx
> +import React from 'react';
Article list используется в MainView и Profile

2022-02-09 06:17 UTC, gold22 commented on src/components/common/ArticleList/ArticleList.jsx
> +import React from 'react';
ок

2022-02-09 06:30 UTC, AlexanderIlinykhDev commented on src/components/common/ArticlePreview/ArticlePreview.jsx
> +import React from 'react';
А если он только в одном компоненте используется я могу его вложить внутрь папки с внешним компонентом?

2022-02-09 06:33 UTC, gold22 commented on src/components/common/ArticlePreview/ArticlePreview.jsx
> +import React from 'react';
да, лучше в папку вместе с компонентом его положить

2022-02-09 06:37 UTC, gold22 commented on src/components/App/App.jsx
> +            <Route exact path='/' component={Home} />
тут "

2022-02-09 06:38 UTC, gold22 commented on src/components/Home/MainView.js
> +          href=''
тут "

2022-02-09 06:39 UTC, gold22 commented on src/components/ProfileFavorites.js
> +      <ul className='nav nav-pills outline-active'>
тут "

2022-02-09 06:40 UTC, gold22 commented on src/components/ProfileFavorites.js
> +        <li className='nav-item'>
тут "

2022-02-09 06:40 UTC, gold22 commented on src/components/common/ArticleList/ArticleList.jsx
> +    return <div className='article-preview'>No articles are here... yet.</div>;
не переведено

2022-02-09 06:56 UTC, gold22 approved these changes

2022-02-09 07:31 UTC, merged