FollowUserButton styled
08-pk-team-03/react-project-kitchen-frontend pull request #6
Opened 2021-12-04 17:30 UTC by AlexanderIlinykhDev

Вынес в src/components/common, стилизовал, застопорился с тем как сделать кнопку универсальной для остальных компонентов

2021-12-04 17:47 UTC, gold22 commented on src/components/Profile.js
> -import React from 'react';
Если начал менять этот компонент, перенеси его сразу в отдельную папку components/Profile

2021-12-04 17:49 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +const FollowUserButton = (props) => {
нужно переименовать в Button, чтобы этот компонент можно было везде использовать

2021-12-04 17:50 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +  if (props.isUser) {
логика рисовать кнопку или нет должна быть в том месте где она используется

2021-12-04 17:54 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +  const handleClick = (ev) => {
хендлер также нужно вынести в место где кнопка используется, и сюда передавать его в пропсе onClick

2021-12-04 17:55 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +      {props.user.following ? (
иконку нужно передавать через пропсы, взяв ее отсюда src/images/icons.js

2021-12-04 17:56 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +      {props.user.following ? "Подписаться" : "Отписаться"}
текст передавать через пропсы, например в параметре title

2021-12-04 17:58 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.module.css
> +.active {
думаю нужно выделить отдельный класс button, где будет все кроме цвета, а в классах active и inactive пусть будет только цвет

2021-12-04 17:59 UTC, gold22 commented on src/components/common/FollowUserButton/FollowUserButton.js
> +    <button className={stylesFollowUserButton.active} onClick={handleClick}>
признак активности кнопки нужно передавать через пропсы

2021-12-04 18:06 UTC, gold22 requested changes
написал что исправить

2021-12-04 18:41 UTC, AlexanderIlinykhDev commented on src/components/Profile.js
> -import React from 'react';
+

2021-12-04 18:41 UTC, AlexanderIlinykhDev commented on src/components/common/FollowUserButton/FollowUserButton.js
> +const FollowUserButton = (props) => {
+

2021-12-04 18:42 UTC, AlexanderIlinykhDev commented on src/components/common/FollowUserButton/FollowUserButton.js
> +  const handleClick = (ev) => {
+

2021-12-05 12:21 UTC, gold22 commented on src/components/common/Button/Button.js
> +const FollowUserButton = ({ onClick, children, isActive }) => {
Нужно переименовать в Button

2021-12-05 12:23 UTC, gold22 commented on src/components/common/Button/Button.js
> +  const [buttonAddStyle, setButtonAddStyle] = useState(stylesButton.active);
Состояние не нужно здесь, при изменении свойств компонент автоматом перерисуется

2021-12-05 12:24 UTC, gold22 commented on src/components/common/Button/Button.js
> +
Можно просто
```
const buttonAddStyle = isActive ? stylesButton.active : stylesButton.inactive;
```

2021-12-05 12:27 UTC, gold22 commented on src/components/Profile/Profile.js
> +                    {" "}
Не нужно вот это все как children передавать
```
                    {" "}
                    {profile.following ? <MinusIcon /> : <PlusIcon />}
                    &nbsp;
                    {profile.following ? "Отписаться" : "Подписаться"}
```
а то {" "} и &nbsp; придется по всему коду копировать, передай просто иконку и название как свойства icon и title, а внутри компонента Button их уже отформатировать как надо. И свойство icon должно быть опциональным.

2021-12-05 15:20 UTC, gold22 commented on src/components/Profile/Profile.js
> +      const ButtonTitle = profile.following ? "Отписаться" : "Подписаться";
-> buttonTitle

2021-12-05 15:23 UTC, gold22 commented on src/components/common/Button/Button.js
> +      <div
тут мне кажется нужно прямо
{icon &&
  <div>
  </div>
}

2021-12-05 16:51 UTC, gold22 commented on src/components/common/Button/Button.js
> +      {icon && <div>&nbsp;</div>}
два раза icon

2021-12-05 18:26 UTC, AlexanderIlinykhDev commented on src/components/common/Button/Button.js
> +      {icon && <div>&nbsp;</div>}
Но если оставить только {icon && <div>&nbsp;</div>} то он не выводит иконку

2021-12-05 18:29 UTC, gold22 commented on src/components/common/Button/Button.js
> +      {icon && <div>&nbsp;</div>}
надо как то так
```
{icon &&
	icon
	<div>&nbsp;</div>
}

{icon &&
	<>
		icon
		<div>&nbsp;</div>
	</>
}
```

2021-12-06 03:58 UTC, gold22 approved these changes

2021-12-06 10:22 UTC, merged